### ISSUE TITLE
Los gráficos no quedan cada 1 minuto sino que se van apilando

### ISSUE THREAD

**Issue by silva96** [ns4lin4s/bike-trail#1]
el total de bicicletas en general es cercano a 2000 bicicletas

Se me hace la idea de que se están agrupando mal la data por minuto ya que en vez de cada 1 minuto, aparecen solo 2 grupos de data.

![image](https://user-images.githubusercontent.com/4019924/55849838-0ad01180-5b20-11e9-9477-c05c7946b4f7.png)

No es necesario que lo arregles, pero lo dejo como info.

**Comment by ns4lin4s** [comment]
Gracias, por el feedback.

**Comment by ns4lin4s** [comment]
Corregido.
